spring.application.name=settlement_service

server.port=8083

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

# EXPENSE SERVICE
expense-service.url=${EXPENSE_SERVICE_URL:http://localhost:8082}

# FEIGN
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.client.config.default.logger-level=basic

# LOGGING
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG