spring.application.name=expense_service

server.port=8082

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/split_bill}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

# AUTH SERVICE
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}

